categories:
    path: /categories
    methods: [GET]
    controller: App\Controller\CategoryController::getAllCategories

category_post:
    path: /categories
    methods: [POST]
    controller: App\Controller\CategoryController::getCategoryByName

category:
  path: /categories/{id}
  methods: [GET]
  controller: App\Controller\CategoryController::getCategory

category_delete:
  path: /categories/{id}
  methods: [DELETE]
  controller: App\Controller\CategoryController::deleteCategory

category_create:
  path: /categories/{id}
  methods: [PUT]
  controller: App\Controller\CategoryController::createCategory
